apiVersion: "test.prakash.com/v1alpha1"
kind: "KafkaTopic"
metadata:
  name: "cruise-control-metrics-topic"
spec:
  name: "__CruiseControlMetrics"
  partition: "3"
  replication: "5"
  cluster: "DC1-dev-shared-app"